import {
  FileTextOutlined,
  FolderOutlined,
} from "@ant-design/icons";
import type { ReactNode } from "react";

import icon_astro from "./material_icons/astro.svg?react";
import icon_c from "./material_icons/c.svg?react";
import icon_console from "./material_icons/console.svg?react";
import icon_cpp from "./material_icons/cpp.svg?react";
import icon_css from "./material_icons/css.svg?react";
import icon_database from "./material_icons/database.svg?react";
import icon_docker from "./material_icons/docker.svg?react";
import icon_document from "./material_icons/document.svg?react";
import icon_editorconfig from "./material_icons/editorconfig.svg?react";
import icon_eslint from "./material_icons/eslint.svg?react";
import icon_file from "./material_icons/file.svg?react";
import icon_git from "./material_icons/git.svg?react";
import icon_go from "./material_icons/go.svg?react";
import icon_graphql from "./material_icons/graphql.svg?react";
import icon_h from "./material_icons/h.svg?react";
import icon_hpp from "./material_icons/hpp.svg?react";
import icon_html from "./material_icons/html.svg?react";
import icon_image from "./material_icons/image.svg?react";
import icon_java from "./material_icons/java.svg?react";
import icon_javascript from "./material_icons/javascript.svg?react";
import icon_json from "./material_icons/json.svg?react";
import icon_less from "./material_icons/less.svg?react";
import icon_log from "./material_icons/log.svg?react";
import icon_markdown from "./material_icons/markdown.svg?react";
import icon_mdx from "./material_icons/mdx.svg?react";
import icon_npm from "./material_icons/npm.svg?react";
import icon_objective_c from "./material_icons/objective-c.svg?react";
import icon_objective_cpp from "./material_icons/objective-cpp.svg?react";
import icon_pdf from "./material_icons/pdf.svg?react";
import icon_powershell from "./material_icons/powershell.svg?react";
import icon_prettier from "./material_icons/prettier.svg?react";
import icon_prisma from "./material_icons/prisma.svg?react";
import icon_proto from "./material_icons/proto.svg?react";
import icon_python from "./material_icons/python.svg?react";
import icon_react from "./material_icons/react.svg?react";
import icon_react_ts from "./material_icons/react_ts.svg?react";
import icon_rust from "./material_icons/rust.svg?react";
import icon_sass from "./material_icons/sass.svg?react";
import icon_settings from "./material_icons/settings.svg?react";
import icon_stylus from "./material_icons/stylus.svg?react";
import icon_svelte from "./material_icons/svelte.svg?react";
import icon_svg from "./material_icons/svg.svg?react";
import icon_table from "./material_icons/table.svg?react";
import icon_toml from "./material_icons/toml.svg?react";
import icon_tune from "./material_icons/tune.svg?react";
import icon_typescript from "./material_icons/typescript.svg?react";
import icon_vue from "./material_icons/vue.svg?react";
import icon_word from "./material_icons/word.svg?react";
import icon_xml from "./material_icons/xml.svg?react";
import icon_yaml from "./material_icons/yaml.svg?react";
import icon_zip from "./material_icons/zip.svg?react";

// AUTO-GENERATED by scripts/generate-project-preview-file-icons.mjs
// Source: https://unpkg.com/material-icon-theme/dist/material-icons.json
// Do not edit manually.
const FOLDER_ICON = <FolderOutlined style={{ color: "#faad14" }} />;
const TEXT_ICON = <FileTextOutlined style={{ color: "#666" }} />;
const SVG_ICON_STYLE: React.CSSProperties = { width: 14, height: 14, objectFit: "contain" };
const makeSvgIcon = (IconComponent: React.ComponentType<React.SVGProps<SVGSVGElement>>): ReactNode => (
  <IconComponent style={SVG_ICON_STYLE} />
);

export const PROJECT_PREVIEW_DIRECTORY_ICONS = {
  directory: FOLDER_ICON,
  folder: FOLDER_ICON,
  file: TEXT_ICON,
  "7z": makeSvgIcon(icon_zip),
  "astro": makeSvgIcon(icon_astro),
  "bash": makeSvgIcon(icon_console),
  "bz2": makeSvgIcon(icon_zip),
  "c": makeSvgIcon(icon_c),
  "cc": makeSvgIcon(icon_cpp),
  "cjs": makeSvgIcon(icon_javascript),
  "conf": makeSvgIcon(icon_settings),
  "cpp": makeSvgIcon(icon_cpp),
  "css": makeSvgIcon(icon_css),
  "csv": makeSvgIcon(icon_table),
  "cts": makeSvgIcon(icon_typescript),
  "cxx": makeSvgIcon(icon_cpp),
  "doc": makeSvgIcon(icon_word),
  "dockerfile": makeSvgIcon(icon_docker),
  "docx": makeSvgIcon(icon_word),
  "editorconfig": makeSvgIcon(icon_editorconfig),
  "env": makeSvgIcon(icon_tune),
  "eslintrc": makeSvgIcon(icon_eslint),
  "fish": makeSvgIcon(icon_console),
  "gif": makeSvgIcon(icon_image),
  "gitattributes": makeSvgIcon(icon_git),
  "gitignore": makeSvgIcon(icon_git),
  "go": makeSvgIcon(icon_go),
  "gql": makeSvgIcon(icon_graphql),
  "graphql": makeSvgIcon(icon_graphql),
  "gz": makeSvgIcon(icon_zip),
  "h": makeSvgIcon(icon_h),
  "hpp": makeSvgIcon(icon_hpp),
  "htm": makeSvgIcon(icon_html),
  "html": makeSvgIcon(icon_html),
  "hxx": makeSvgIcon(icon_hpp),
  "ico": makeSvgIcon(icon_image),
  "ini": makeSvgIcon(icon_settings),
  "java": makeSvgIcon(icon_java),
  "jpeg": makeSvgIcon(icon_image),
  "jpg": makeSvgIcon(icon_image),
  "js": makeSvgIcon(icon_javascript),
  "json": makeSvgIcon(icon_json),
  "jsonc": makeSvgIcon(icon_json),
  "jsx": makeSvgIcon(icon_react),
  "less": makeSvgIcon(icon_less),
  "log": makeSvgIcon(icon_log),
  "m": makeSvgIcon(icon_objective_c),
  "markdown": makeSvgIcon(icon_markdown),
  "md": makeSvgIcon(icon_markdown),
  "mdx": makeSvgIcon(icon_mdx),
  "mjs": makeSvgIcon(icon_javascript),
  "mm": makeSvgIcon(icon_objective_cpp),
  "mts": makeSvgIcon(icon_typescript),
  "npmrc": makeSvgIcon(icon_npm),
  "pdf": makeSvgIcon(icon_pdf),
  "png": makeSvgIcon(icon_image),
  "prettierignore": makeSvgIcon(icon_prettier),
  "prettierrc": makeSvgIcon(icon_prettier),
  "prisma": makeSvgIcon(icon_prisma),
  "proto": makeSvgIcon(icon_proto),
  "ps1": makeSvgIcon(icon_powershell),
  "py": makeSvgIcon(icon_python),
  "rar": makeSvgIcon(icon_zip),
  "rs": makeSvgIcon(icon_rust),
  "sass": makeSvgIcon(icon_sass),
  "scss": makeSvgIcon(icon_sass),
  "sh": makeSvgIcon(icon_console),
  "sql": makeSvgIcon(icon_database),
  "styl": makeSvgIcon(icon_stylus),
  "stylus": makeSvgIcon(icon_file),
  "svelte": makeSvgIcon(icon_svelte),
  "svg": makeSvgIcon(icon_svg),
  "tar": makeSvgIcon(icon_zip),
  "tgz": makeSvgIcon(icon_zip),
  "toml": makeSvgIcon(icon_toml),
  "ts": makeSvgIcon(icon_typescript),
  "tsbuildinfo": makeSvgIcon(icon_json),
  "tsx": makeSvgIcon(icon_react_ts),
  "txt": makeSvgIcon(icon_document),
  "vue": makeSvgIcon(icon_vue),
  "webp": makeSvgIcon(icon_image),
  "xhtml": makeSvgIcon(icon_html),
  "xls": makeSvgIcon(icon_table),
  "xlsx": makeSvgIcon(icon_table),
  "xml": makeSvgIcon(icon_xml),
  "yaml": makeSvgIcon(icon_yaml),
  "yml": makeSvgIcon(icon_yaml),
  "zip": makeSvgIcon(icon_zip),
  "zsh": makeSvgIcon(icon_console),
} as const;
