"""conversations 表增加 last_message_updated_at 字段

Revision ID: 01fb8247599b
Revises: 6fc87d2a678f
Create Date: 2025-11-10 22:42:00.755886

"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '01fb8247599b'
down_revision = '6fc87d2a678f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加列为可空
    op.add_column(
        'conversations',
        sa.Column('last_message_updated_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # 为现有记录设置默认值
    op.execute(
        """
        UPDATE conversations
        SET last_message_updated_at = COALESCE(last_message_created_at, created_at, NOW())
        WHERE last_message_updated_at IS NULL
    """
    )
    op.execute(
        """
        UPDATE messages
        SET updated_at = created_at
        WHERE updated_at IS NULL
    """
    )

    # 然后将列设置为不可空
    op.alter_column(
        'conversations',
        'last_message_updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        'messages',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updated_at')
    op.drop_column('conversations', 'last_message_updated_at')
    # ### end Alembic commands ###
