"""同步外键、索引与 server_default（与当前模型一致）

Revision ID: 667cf79bd836
Revises: h9i0j1k2l3m4
Create Date: 2026-02-07 12:25:33.841321

- conversation_contexts: 添加 conversation_id -> conversations.id 外键 (CASCADE)
- user_profile_items: 添加 user_id -> users.id 外键、ix_user_profile_items_id 索引
- user_profile_items: created_at/updated_at 移除 server_default=now()
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "667cf79bd836"
down_revision = "h9i0j1k2l3m4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "conversation_contexts_conversation_id_fkey",
        "conversation_contexts",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "user_profile_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_profile_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_user_profile_items_id"), "user_profile_items", ["id"], unique=False
    )
    op.create_foreign_key(
        "user_profile_items_user_id_fkey",
        "user_profile_items",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_profile_items_user_id_fkey", "user_profile_items", type_="foreignkey"
    )
    op.drop_index(op.f("ix_user_profile_items_id"), table_name="user_profile_items")
    op.alter_column(
        "user_profile_items",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_profile_items",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.drop_constraint(
        "conversation_contexts_conversation_id_fkey",
        "conversation_contexts",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
