"""chore: 初始化数据库迁移

Revision ID: 6fc87d2a678f
Revises: 
Create Date: 2025-11-10 11:53:18.030549

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision = '6fc87d2a678f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'created_by',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=None,
                    existing_nullable=False)
    # 先为 NULL 值设置默认值（当前时间戳）
    op.execute(
        "UPDATE conversations SET last_message_created_at = conversations.created_at WHERE last_message_created_at IS NULL")
    op.alter_column('conversations', 'last_message_created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.alter_column('messages', 'conversation_id',
                    existing_type=sa.VARCHAR(length=36),
                    nullable=True)
    op.alter_column('messages', 'status',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=None,
                    existing_nullable=False)
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.create_index(op.f('ix_messages_created_at'),
                    'messages', ['created_at'], unique=False)
    op.create_foreign_key(None, 'messages', 'conversations', [
                          'conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.create_index(op.f('ix_messages_timestamp'),
                    'messages', ['created_at'], unique=False)
    op.alter_column('messages', 'status',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=sa.text("'pending'::character varying"),
                    existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
                    existing_type=sa.VARCHAR(length=36),
                    nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.alter_column('conversations', 'last_message_created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    op.alter_column('conversations', 'created_by',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=sa.text("'default'::character varying"),
                    existing_nullable=False)
    # ### end Alembic commands ###
