"""增加 token_stats 计数统计字段

Revision ID: ba2310dcb4e9
Revises: c7ba74ff1c71
Create Date: 2026-01-09 22:42:44.517809

"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel  # noqa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ba2310dcb4e9"
down_revision = "c7ba74ff1c71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("token_stats", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "token_stats")
    # ### end Alembic commands ###
