"""添加component_tool_calls字段

Revision ID: c7ba74ff1c71
Revises: f3a5cb0a5d3a
Create Date: 2025-12-23 21:59:36.940190

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision = 'c7ba74ff1c71'
down_revision = 'f3a5cb0a5d3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('component_tool_calls', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('component_tool_calls_duration', sa.Float(), nullable=True))
    op.alter_column('messages', 'tool_calls_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='工具调用耗时（秒）',
               existing_nullable=True)
    op.alter_column('messages', 'reasoning_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='推理耗时（秒）',
               existing_nullable=True)
    op.alter_column('messages', 'content_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='内容生成耗时（秒）',
               existing_nullable=True)
    op.alter_column('messages', 'total_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='总耗时（秒）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'total_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='总耗时（秒）',
               existing_nullable=True)
    op.alter_column('messages', 'content_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='内容生成耗时（秒）',
               existing_nullable=True)
    op.alter_column('messages', 'reasoning_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='推理耗时（秒）',
               existing_nullable=True)
    op.alter_column('messages', 'tool_calls_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='工具调用耗时（秒）',
               existing_nullable=True)
    op.drop_column('messages', 'component_tool_calls_duration')
    op.drop_column('messages', 'component_tool_calls')
    # ### end Alembic commands ###

