"""添加消息耗时字段

Revision ID: f3a5cb0a5d3a
Revises: f557f3662fc1
Create Date: 2025-01-27 12:00:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision = 'f3a5cb0a5d3a'
down_revision = 'f557f3662fc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加耗时字段，允许为空
    op.add_column('messages', sa.Column(
        'tool_calls_duration', sa.Float(), nullable=True,
        comment='工具调用耗时（秒）'))
    op.add_column('messages', sa.Column(
        'reasoning_duration', sa.Float(), nullable=True,
        comment='推理耗时（秒）'))
    op.add_column('messages', sa.Column(
        'content_duration', sa.Float(), nullable=True,
        comment='内容生成耗时（秒）'))
    op.add_column('messages', sa.Column(
        'total_duration', sa.Float(), nullable=True,
        comment='总耗时（秒）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'total_duration')
    op.drop_column('messages', 'content_duration')
    op.drop_column('messages', 'reasoning_duration')
    op.drop_column('messages', 'tool_calls_duration')
    # ### end Alembic commands ###
