"""更新数据库 user 表,增加 last_login_at, last_logout_at, sub 等字段

Revision ID: f557f3662fc1
Revises: 01fb8247599b
Create Date: 2025-11-19 18:39:46.659063

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision = 'f557f3662fc1'
down_revision = '01fb8247599b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_logout_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_sub'), 'users', ['sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sub'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'last_login_type')
    op.drop_column('users', 'last_logout_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'sub')
    # ### end Alembic commands ###

