[project]
name = "webhook"
version = "0.1.0"
description = "GitHub Webhook for auto deployment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "github-webhook>=1.0.4",
    "python-dotenv>=1.2.1",
    "loguru>=0.7.3",
    "jinja2>=3.1.6",
]

[tool.uv]
index-url = "https://mirrors.aliyun.com/pypi/simple/"
